import sys
import os
from crontab import CronTab
path=sys.argv[1]
f=open(path+"script1.py",'w')
f.write("import MySQLdb as mdb\n")
f.write("con=mdb.connect('localhost','root','')\n")
f.write("c=con.cursor()\n")
f.write('c.execute("CREATE DATABASE time_test;")\n')
f.write('c.execute("CREATE TABLE test_time (time VARCHAR(10));")\n')
f.write('con.commit()\n')
f.write('c.close()')
f.close()
f=open(path+"script2.py",'w')
f.write("from time import strftime\n")
f.write("import MySQLdb as mdb\n")
f.write("curtime=strftime('%H:%M:%S')\n")
f.write("t=(curtime,)\n")
f.write("con=mdb.connect('localhost','root','','time_test')\n")
f.write("c=con.cursor()\n")
f.write('c.execute("INSERT INTO test_time VALUES(?)",t)\n')
f.write('con.commit()\n')
f.write('c.close()\n')
f.close()
os.system("python "+path+"script1.py")
tab = CronTab()
job = tab.new('python '+path+'script2.py')
job.minute.during(0,59).every(10)
tab.write()
